import { randomUUID } from "node:crypto";
import { commandServiceToken, SessionConflictError, sessionStoreToken, type CommandDefinition, type CommandDescriptor, type CommandExecution, type CommandResult, type CommandService, type SealHarnessEvents, type SessionEvent, type SessionId, type SessionStore } from "@seal-harness/core";
import { definePlugin } from "@seal-harness/kernel";
export function parseCommand(line: string): { name: string; rawInput: string } | undefined { const match = /^\/([a-z][a-z0-9_-]*)(?=$|[\t\n\r ])/u.exec(line); return match?.[1] === undefined ? undefined : { name: match[1], rawInput: line.slice(match[0].length) }; }
export class DefaultCommandService implements CommandService {
  readonly #commands = new Map<string, CommandDefinition>();
  constructor(readonly sessions: SessionStore, readonly idFactory: () => string = randomUUID) {}
  register(definition: CommandDefinition): () => void { if (!/^[a-z][a-z0-9_-]*$/.test(definition.name)) throw new TypeError("command name must contain lowercase letters, digits, underscore, or hyphen"); if (definition.description.trim() === "" || typeof definition.handler !== "function") throw new TypeError("command requires description and handler"); if (definition.input !== undefined && definition.input.hint.trim() === "") throw new TypeError("command input hint must not be empty"); if (this.#commands.has(definition.name)) throw new Error(`command \"${definition.name}\" is already registered`); this.#commands.set(definition.name, definition); return () => { if (this.#commands.get(definition.name) === definition) this.#commands.delete(definition.name); }; }
  list(): readonly CommandDescriptor[] { return [...this.#commands.values()].map((x) => Object.freeze({ name: x.name, description: x.description, ...(x.input === undefined ? {} : { input: Object.freeze({ ...x.input }) }) })); }
  async execute(sessionId: SessionId, line: string, signal: AbortSignal = new AbortController().signal): Promise<CommandExecution | undefined> { const parsed = parseCommand(line); if (parsed === undefined) return undefined; const definition = this.#commands.get(parsed.name); if (definition === undefined) return undefined; signal.throwIfAborted(); const commandId = `command-${this.idFactory()}`; await append(this.sessions, sessionId, [{ type: "command.run", payload: { commandId, name: definition.name, ...(definition.recordInput === false ? {} : { args: parsed.rawInput }) } }]); let result: CommandResult; try { result = await withAbort(Promise.resolve(definition.handler({ commandId, sessionId, rawInput: parsed.rawInput, signal })), signal); if (result.kind !== "success" && result.kind !== "error") throw new Error("command returned an invalid result"); } catch (error) { result = { kind: "error", text: error instanceof Error ? error.message : String(error) }; } await append(this.sessions, sessionId, [{ type: "command.done", payload: { commandId, kind: result.kind, ...(result.text === undefined ? {} : { text: result.text }) } }]); return { commandId, result }; }
}
async function append(store: SessionStore, id: SessionId, events: readonly SessionEvent[]): Promise<void> { const current = await store.read(id); if (current === undefined) throw new Error(`Session not found: ${id}`); try { await store.append({ id, expectedVersion: current.version, events }); } catch (error) { if (!(error instanceof SessionConflictError)) throw error; const latest = await store.read(id); if (latest === undefined) throw new Error(`Session not found: ${id}`); await store.append({ id, expectedVersion: latest.version, events }); } }
function withAbort<T>(value: Promise<T>, signal: AbortSignal): Promise<T> { if (signal.aborted) return Promise.reject(signal.reason); return new Promise((resolve, reject) => { const abort = () => reject(signal.reason ?? new Error("command aborted")); signal.addEventListener("abort", abort, { once: true }); value.then((x) => { signal.removeEventListener("abort", abort); resolve(x); }, (e) => { signal.removeEventListener("abort", abort); reject(e); }); }); }
export const commandsPlugin = definePlugin<undefined, SealHarnessEvents>({ name: "commands", provides: [commandServiceToken], requires: [sessionStoreToken], setup(context) { context.provide(commandServiceToken, new DefaultCommandService(context.use(sessionStoreToken))); } });
