import { agentPresetServiceToken, contextServiceToken, SessionConflictError, sessionStoreToken, toolServiceToken, type AgentPresetAuthority, type AgentPresetRow, type AgentPresetService, type AgentPresetSpec, type ContextService, type SealHarnessEvents, type SessionEvent, type SessionId, type SessionSnapshot, type SessionStore, type ToolService } from "@seal-harness/core";
import { definePlugin } from "@seal-harness/kernel";

export interface AgentPresetsConfig { readonly default?: string; readonly presets?: Readonly<Record<string, AgentPresetSpec>> }
const DEFAULT_PRESETS: Readonly<Record<string, AgentPresetSpec>> = Object.freeze({
  standard: { name: "Standard", description: "Full coding agent with all composed capabilities.", systemPrompt: "Operate as a full coding agent. Use the available tools and skills needed to complete the task." },
  minimal: { name: "Minimal", description: "Small editing agent with file reading, replacement, and persistent terminal tools.", systemPrompt: "Operate as a minimal coding agent. Prefer precise reads, text replacement, and the persistent terminal.", tools: { allow: ["read_file", "replace_text", "terminal_start", "terminal_send", "terminal_read", "terminal_list", "terminal_kill"] } },
});

export class DurableAgentPresetService implements AgentPresetService {
  readonly defaultPreset: string; readonly presets: Readonly<Record<string, AgentPresetSpec>>; readonly #disposeContext: () => void; readonly #queues = new Map<SessionId, Promise<void>>(); readonly #current = new Map<SessionId, string>(); readonly #externalCurrent = new Set<SessionId>(); readonly #restrictions = new Map<SessionId, () => void>(); readonly #authorities = new Set<AgentPresetAuthority>(); readonly #externalRows = new Map<string, AgentPresetRow>();
  constructor(readonly sessions: SessionStore, readonly tools: ToolService, readonly contexts: ContextService, config: AgentPresetsConfig = {}) {
    this.presets = config.presets ?? DEFAULT_PRESETS; this.defaultPreset = config.default ?? "standard"; this.#resolve(this.defaultPreset);
    this.#disposeContext = contexts.register({ name: "agent-preset", contribute: async (request) => { const id = this.#current.get(request.sessionId) ?? await this.current(request.sessionId); const preset = this.#externalCurrent.has(request.sessionId) ? undefined : this.presets[id]; return preset?.systemPrompt === undefined ? undefined : { systemPrompt: preset.systemPrompt }; } });
  }
  list(): readonly AgentPresetRow[] { const local = Object.entries(this.presets).map(([id, preset]) => ({ id, name: preset.name ?? id, ...(preset.description === undefined ? {} : { description: preset.description }), isDefault: id === this.defaultPreset })); return [...local, ...[...this.#externalRows.values()].filter((row) => this.presets[row.id] === undefined)]; }
  async validate(id: string): Promise<void> { const resolved = await this.#resolveAny(id); if (resolved.kind === "external") return; const restriction = resolved.preset.tools; if (restriction === undefined) return; if (this.tools.restrict === undefined) throw new Error("active ToolService does not support agent preset restrictions"); const dispose = this.tools.restrict(restriction, { ownerSession: `preset-validation-${id}` as SessionId }); dispose(); }
  registerAuthority(authority: AgentPresetAuthority): () => void { this.#authorities.add(authority); return () => { this.#authorities.delete(authority); for (const [id, row] of this.#externalRows) if (this.presets[id] === undefined) this.#externalRows.delete(id); }; }
  async current(sessionId: SessionId): Promise<string> { const cached = this.#current.get(sessionId); if (cached !== undefined) return cached; const session = await requiredSession(this.sessions, sessionId); const preset = selected(session) ?? metadataPreset(session) ?? this.defaultPreset; const resolved = await this.#resolveAny(preset); this.#current.set(sessionId, preset); if (resolved.kind === "external") this.#externalCurrent.add(sessionId); else this.#externalCurrent.delete(sessionId); return preset; }
  systemPrompt(sessionId: SessionId): string | undefined { return this.#externalCurrent.has(sessionId) ? undefined : this.presets[this.#current.get(sessionId) ?? this.defaultPreset]?.systemPrompt; }
  dispose(): void { this.#disposeContext(); for (const dispose of this.#restrictions.values()) dispose(); this.#restrictions.clear(); }
  set(sessionId: SessionId, preset: string): Promise<string> { return this.#serial(sessionId, async () => { const resolved = await this.#resolveAny(preset); const session = await requiredSession(this.sessions, sessionId); const current = selected(session) ?? metadataPreset(session); if (current === preset) { if (resolved.kind === "local") { this.#externalCurrent.delete(sessionId); this.#applyTools(sessionId, preset); } else { this.#externalCurrent.add(sessionId); this.#clearTools(sessionId); } return preset; } if (!blank(session)) throw new Error(`session "${sessionId}" has already started; its agent preset is fixed`); const next = await append(this.sessions, session, [{ type: "agent-preset.selected", payload: { preset } }]); this.#current.set(sessionId, preset); if (resolved.kind === "local") { this.#externalCurrent.delete(sessionId); this.#applyTools(sessionId, preset); } else { this.#externalCurrent.add(sessionId); this.#clearTools(sessionId); } return selected(next) ?? preset; }); }
  initialize(session: SessionSnapshot): Promise<SessionSnapshot> { return this.#serial(session.id, async () => { let latest = await requiredSession(this.sessions, session.id); let preset = selected(latest) ?? metadataPreset(latest); if (preset === undefined) { preset = this.defaultPreset; latest = await append(this.sessions, latest, [{ type: "agent-preset.selected", payload: { preset } }]); } const resolved = await this.#resolveAny(preset); this.#current.set(session.id, preset); if (resolved.kind === "local") { this.#externalCurrent.delete(session.id); this.#applyTools(session.id, preset); } else { this.#externalCurrent.add(session.id); this.#clearTools(session.id); await resolved.authority.prepare(latest, preset); latest = await requiredSession(this.sessions, session.id); } return latest; }); }
  #resolve(id: string): AgentPresetSpec { const preset = this.presets[id]; if (preset === undefined) throw new Error(`unknown agent preset "${id}" (known: ${Object.keys(this.presets).join(", ")})`); return preset; }
  async #resolveAny(id: string): Promise<{ readonly kind: "local"; readonly preset: AgentPresetSpec } | { readonly kind: "external"; readonly authority: AgentPresetAuthority }> { for (const authority of this.#authorities) { const row = await authority.resolve(id); if (row === undefined) continue; if (row.broken !== undefined) throw new Error(`agent preset "${id}" is broken: ${row.broken}`); this.#externalRows.set(id, row); return { kind: "external", authority }; } const local = this.presets[id]; if (local !== undefined) return { kind: "local", preset: local }; throw new Error(`unknown agent preset "${id}" (known: ${this.list().map((row) => row.id).join(", ")})`); }
  #clearTools(sessionId: SessionId): void { this.#restrictions.get(sessionId)?.(); this.#restrictions.delete(sessionId); }
  #applyTools(sessionId: SessionId, id: string): void { this.#restrictions.get(sessionId)?.(); this.#restrictions.delete(sessionId); const restriction = this.#resolve(id).tools; if (restriction !== undefined) { if (this.tools.restrict === undefined) throw new Error("active ToolService does not support agent preset restrictions"); this.#restrictions.set(sessionId, this.tools.restrict(restriction, { ownerSession: sessionId })); } }
  #serial<T>(id: SessionId, work: () => Promise<T>): Promise<T> { const previous = this.#queues.get(id) ?? Promise.resolve(); const result = previous.catch(() => undefined).then(work); const tail = result.then(() => undefined, () => undefined); this.#queues.set(id, tail); return result.finally(() => { if (this.#queues.get(id) === tail) this.#queues.delete(id); }); }
}
function selected(session: SessionSnapshot): string | undefined { let value: string | undefined; for (const entry of session.events) if (entry.event.type === "agent-preset.selected") value = entry.event.payload.preset; return value; }
function metadataPreset(session: SessionSnapshot): string | undefined { const created = session.events.find((entry) => entry.event.type === "session.created")?.event; return created?.type === "session.created" && typeof created.payload.metadata?.agentPreset === "string" ? created.payload.metadata.agentPreset : undefined; }
function blank(session: SessionSnapshot): boolean { return !session.events.some((entry) => entry.event.type === "message.appended" || entry.event.type === "tool.started" || entry.event.type === "run.started"); }
async function requiredSession(store: SessionStore, id: SessionId): Promise<SessionSnapshot> { const value = await store.read(id); if (value === undefined) throw new Error(`Session not found: ${id}`); return value; }
async function append(store: SessionStore, snapshot: SessionSnapshot, events: readonly SessionEvent[]): Promise<SessionSnapshot> { try { return await store.append({ id: snapshot.id, expectedVersion: snapshot.version, events }); } catch (error) { if (!(error instanceof SessionConflictError)) throw error; const latest = await requiredSession(store, snapshot.id); return store.append({ id: latest.id, expectedVersion: latest.version, events }); } }
export const agentPresetsPlugin = definePlugin<AgentPresetsConfig, SealHarnessEvents>({ name: "agent-presets", provides: [agentPresetServiceToken], requires: [sessionStoreToken, toolServiceToken, contextServiceToken], setup(context, config) { const service = new DurableAgentPresetService(context.use(sessionStoreToken), context.use(toolServiceToken), context.use(contextServiceToken), config); context.provide(agentPresetServiceToken, service); context.effect(() => service.dispose()); } });
