export const styles = `
.zz-cap-form-grid{display:grid;gap:12px;border:0;padding:0;grid-template-columns:repeat(auto-fit,minmax(220px,1fr))}.zz-cap-panel fieldset{min-width:0}.zz-cap-panel pre{white-space:pre-wrap;overflow-wrap:anywhere}.zz-cap-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:16px 0}.zz-cap-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:16px}.zz-cap-panel form{display:grid;gap:12px}.zz-cap-panel form label{display:grid;gap:4px}.zz-cap-panel textarea{min-height:100px;resize:vertical}
.zz-cap-panel{height:100%;overflow:auto;box-sizing:border-box;padding:calc(28px + var(--dsh-frame-top-clearance,0px)) 32px 32px;color:var(--dsw-alias-label-primary,#23262d);font:14px/1.6 system-ui,sans-serif}
.zz-cap-panel header{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-bottom:24px}.zz-cap-panel h1{font-size:26px;line-height:1.25;margin:0 0 8px}.zz-cap-panel h2{font-size:17px;margin:0}.zz-cap-panel h3{font-size:15px}
.zz-cap-panel p{margin:8px 0}.zz-cap-eyebrow{font-size:12px;color:var(--dsw-alias-label-secondary,#596273);letter-spacing:.08em}.zz-cap-muted,.zz-cap-panel small{color:var(--dsw-alias-label-secondary,#596273)}
.zz-cap-panel button,.zz-cap-panel input,.zz-cap-panel select,.zz-cap-panel textarea{font:inherit;border:1px solid color-mix(in srgb,currentColor 22%,transparent);border-radius:7px;padding:8px 12px;background:transparent;color:inherit;box-sizing:border-box;min-height:40px}
.zz-cap-panel button{cursor:pointer}.zz-cap-panel button:hover:not(:disabled){background:color-mix(in srgb,currentColor 7%,transparent)}.zz-cap-panel button:disabled{opacity:.5;cursor:not-allowed}.zz-cap-panel :focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#3765c7);outline-offset:3px}
.zz-cap-tabs{display:flex;gap:8px;border-bottom:1px solid color-mix(in srgb,currentColor 15%,transparent);padding-bottom:16px;margin-bottom:20px;flex-wrap:wrap}.zz-cap-tabs button[aria-pressed=true]{background:color-mix(in srgb,var(--dsw-alias-brand-primary,#3765c7) 12%,transparent);border-color:var(--dsw-alias-brand-primary,#3765c7)}
.zz-cap-filters{display:flex;align-items:end;gap:16px;margin:0 0 24px;flex-wrap:wrap}.zz-cap-filters label{display:grid;gap:5px}.zz-cap-filters label:first-child{flex:1;min-width:180px}.zz-cap-filters input{width:100%}
.zz-cap-layout{display:flex;gap:24px;align-items:flex-start}.zz-cap-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:16px;flex:1;min-width:0}.zz-cap-card{border:1px solid color-mix(in srgb,currentColor 15%,transparent);border-radius:10px;padding:20px}.zz-cap-card-heading{display:flex;align-items:baseline;justify-content:space-between;gap:12px}.zz-cap-card p{overflow-wrap:anywhere}.zz-cap-card button{margin-top:12px}
.zz-cap-tags{display:flex;flex-wrap:wrap;gap:6px}.zz-cap-tags span{font-size:12px;padding:2px 8px;border-radius:4px;background:color-mix(in srgb,currentColor 7%,transparent)}
.zz-cap-empty{padding:44px 24px;border:1px dashed color-mix(in srgb,currentColor 25%,transparent);border-radius:10px}.zz-cap-notice{padding:12px 16px;margin:16px 0;background:color-mix(in srgb,var(--dsw-alias-brand-primary,#3765c7) 8%,transparent);border-radius:8px}.zz-cap-notice button+button{margin-left:8px}
.zz-cap-detail{width:340px;max-width:100%;box-sizing:border-box;border:1px solid color-mix(in srgb,currentColor 20%,transparent);padding:20px;border-radius:10px}.zz-cap-detail>h2{margin-top:20px}.zz-cap-version{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:14px 0;border-bottom:1px solid color-mix(in srgb,currentColor 12%,transparent)}
@media(max-width:900px){.zz-cap-layout{flex-direction:column}.zz-cap-detail{width:100%}.zz-cap-list{width:100%}.zz-cap-panel{padding-left:20px;padding-right:20px}}
`
