import { createServiceToken } from "@seal-harness/kernel";
import type { AgentService, SessionInitializer } from "./agent.js";
import type { AttachmentService } from "./attachment.js";
import type { CompactionService } from "./compaction.js";
import type { ContextService } from "./context.js";
import type { CredentialService } from "./credential.js";
import type { ModelService } from "./model.js";
import type { JobService } from "./job.js";
import type { GoalService } from "./goal.js";
import type { ApprovalService, PolicyService } from "./policy.js";
import type { AgentRuntime } from "./runtime.js";
import type { SessionStore } from "./session.js";
import type { SubagentService } from "./subagent.js";
import type { ToolService } from "./tool.js";
import type { TelemetryService } from "./telemetry.js";
import type { TerminalService } from "./terminal.js";
import type { TodoService } from "./todo.js";
import type { PlanModeService } from "./plan.js";
import type { SandboxService } from "./sandbox.js";
import type { ScheduleService } from "./schedule.js";
import type { LspService } from "./lsp.js";
import type { UserQuestionService } from "./interaction.js";
import type { PermissionPresetService } from "./permission.js";
import type { AgentPresetService } from "./preset.js";
import type { CommandService, MessageFeedbackService } from "./command.js";
import type { WebhookRuntime, WebRouteService } from "./webhook.js";
import type { WebAccessService } from "./web.js";
import type { SpillStore } from "./spill.js";
import type { SettingsService } from "./settings.js";
import type { TeamService } from "./team.js";

export const modelServiceToken = createServiceToken<ModelService>("seal-harness.model");
export const runtimeToken = createServiceToken<AgentRuntime>("seal-harness.runtime");
export const sessionStoreToken = createServiceToken<SessionStore>("seal-harness.session-store");
export const toolServiceToken = createServiceToken<ToolService>("seal-harness.tools");
export const policyServiceToken = createServiceToken<PolicyService>("seal-harness.policy");
export const approvalServiceToken = createServiceToken<ApprovalService>("seal-harness.approval");
export const contextServiceToken = createServiceToken<ContextService>("seal-harness.context");
export const credentialServiceToken = createServiceToken<CredentialService>("seal-harness.credentials");
export const agentServiceToken = createServiceToken<AgentService>("seal-harness.agent");
export const compactionServiceToken = createServiceToken<CompactionService>("seal-harness.compaction");
export const telemetryServiceToken = createServiceToken<TelemetryService>("seal-harness.telemetry");
export const attachmentServiceToken = createServiceToken<AttachmentService>("seal-harness.attachments");
export const subagentServiceToken = createServiceToken<SubagentService>("seal-harness.subagents");
export const jobServiceToken = createServiceToken<JobService>("seal-harness.jobs");
export const terminalServiceToken = createServiceToken<TerminalService>("seal-harness.terminals");
export const goalServiceToken = createServiceToken<GoalService>("seal-harness.goals");
export const todoServiceToken = createServiceToken<TodoService>("seal-harness.todos");
export const planModeServiceToken = createServiceToken<PlanModeService>("seal-harness.plan-mode");
export const sandboxServiceToken = createServiceToken<SandboxService>("seal-harness.sandbox");
export const scheduleServiceToken = createServiceToken<ScheduleService>("seal-harness.schedules");
export const lspServiceToken = createServiceToken<LspService>("seal-harness.lsp");
export const userQuestionServiceToken = createServiceToken<UserQuestionService>("seal-harness.user-questions");
export const permissionPresetServiceToken = createServiceToken<PermissionPresetService>("seal-harness.permission-presets");
export const sessionInitializerToken = createServiceToken<SessionInitializer>("seal-harness.session-initializer");
export const agentPresetServiceToken = createServiceToken<AgentPresetService>("seal-harness.agent-presets");
export const commandServiceToken = createServiceToken<CommandService>("seal-harness.commands");
export const messageFeedbackServiceToken = createServiceToken<MessageFeedbackService>("seal-harness.message-feedback");
export const webhookRuntimeToken = createServiceToken<WebhookRuntime>("seal-harness.webhooks");
export const webRouteServiceToken = createServiceToken<WebRouteService>("seal-harness.web-routes");
export const webAccessServiceToken = createServiceToken<WebAccessService>("seal-harness.web-access");
export const spillStoreToken = createServiceToken<SpillStore>("seal-harness.spill-store");
export const settingsServiceToken = createServiceToken<SettingsService>("seal-harness.settings");
export const teamServiceToken = createServiceToken<TeamService>("seal-harness.agent-teams");
