import { createServiceToken } from "@seal-harness/kernel";
import type { AgentService } from "./agent.js";
import type { AttachmentService } from "./attachment.js";
import type { CompactionService } from "./compaction.js";
import type { ContextService } from "./context.js";
import type { CredentialService } from "./credential.js";
import type { ModelService } from "./model.js";
import type { ApprovalService, PolicyService } from "./policy.js";
import type { AgentRuntime } from "./runtime.js";
import type { SessionStore } from "./session.js";
import type { ToolService } from "./tool.js";
import type { TelemetryService } from "./telemetry.js";

export const modelServiceToken = createServiceToken<ModelService>("seal-harness.model");
export const runtimeToken = createServiceToken<AgentRuntime>("seal-harness.runtime");
export const sessionStoreToken = createServiceToken<SessionStore>("seal-harness.session-store");
export const toolServiceToken = createServiceToken<ToolService>("seal-harness.tools");
export const policyServiceToken = createServiceToken<PolicyService>("seal-harness.policy");
export const approvalServiceToken = createServiceToken<ApprovalService>("seal-harness.approval");
export const contextServiceToken = createServiceToken<ContextService>("seal-harness.context");
export const credentialServiceToken = createServiceToken<CredentialService>("seal-harness.credentials");
export const agentServiceToken = createServiceToken<AgentService>("seal-harness.agent");
export const compactionServiceToken = createServiceToken<CompactionService>("seal-harness.compaction");
export const telemetryServiceToken = createServiceToken<TelemetryService>("seal-harness.telemetry");
export const attachmentServiceToken = createServiceToken<AttachmentService>("seal-harness.attachments");
