import React, { useEffect, useState } from 'react'

const newTool = index => ({ name: `http_tool_${index}`, description: '', enabled: true, riskLevel: 'read', inputSchema: { type: 'object', properties: {}, required: [], additionalProperties: false }, request: { method: 'GET', url: '', headers: {}, auth: { type: 'none' }, contentType: 'json', parameters: {} }, response: { format: 'auto' }, timeoutMs: 10000, retry: { maxRetries: 0, backoffMs: 250 } })
export function HttpAdapterEditor({ asset, version, api, close, saved }) {
  const [adapter, setAdapter] = useState(null), [etag, setEtag] = useState(version.etag)
  const [index, setIndex] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(''), [result, setResult] = useState(null)
  const [argumentsValue, setArguments] = useState({}), [credentials, setCredentials] = useState({})
  useEffect(() => {
    const controller = new AbortController()
    api('store/adapter', { id: asset.id, version: version.version }, controller.signal).then(value => {
      setEtag(value.etag)
      setAdapter(value.adapter ?? { schemaVersion: 'stratex.http-adapter/v1', sourceType: 'http_adapter', name: asset.name, description: asset.summary, tools: [newTool(1)] })
    }).catch(error => { if (!controller.signal.aborted) setError(error.message) })
    return () => controller.abort()
  }, [api, asset.id, version.version])
  const tool = adapter?.tools[index]
  const update = patch => setAdapter(current => ({ ...current, tools: current.tools.map((value, position) => position === index ? { ...value, ...patch } : value) }))
  const request = patch => update({ request: { ...tool.request, ...patch } })
  const parameter = (name, patch) => update({ inputSchema: { ...tool.inputSchema, properties: { ...tool.inputSchema.properties, [name]: { ...tool.inputSchema.properties[name], ...patch } } } })
  const auth = patch => request({ auth: { ...tool.request.auth, ...patch } })
  const slots = tool ? [tool.request.auth.credentialSlot, tool.request.auth.usernameCredentialSlot, tool.request.auth.passwordCredentialSlot].filter(Boolean) : []
  async function run(action) { setBusy(true); setError(''); try { await action() } catch (error) { setError(error.message) } finally { setBusy(false) } }
  return <section className="zz-cap-card" aria-label="HTTP 工具编辑"><div className="zz-cap-toolbar"><h2>HTTP 工具 · {version.version}</h2><button disabled={busy} onClick={close}>关闭</button></div>{error && <p role="alert">{error}</p>}{!tool ? <p>正在读取工具定义…</p> : <>
    <nav className="zz-cap-tabs">{adapter.tools.map((value, position) => <button key={position} disabled={busy} aria-pressed={position === index} onClick={() => { setIndex(position); setArguments({}); setResult(null) }}>{value.name || `工具 ${position + 1}`}</button>)}<button disabled={busy} onClick={() => { setAdapter(current => ({ ...current, tools: [...current.tools, newTool(current.tools.length + 1)] })); setIndex(adapter.tools.length) }}>添加工具</button></nav>
    <fieldset disabled={busy} className="zz-cap-form-grid"><label>工具名称<input value={tool.name} onChange={event => update({ name: event.target.value })} pattern="[A-Za-z_][A-Za-z0-9_-]*" /></label><label><input type="checkbox" checked={tool.enabled} onChange={event => update({ enabled: event.target.checked })} />启用工具</label><label>工具说明<input value={tool.description} onChange={event => update({ description: event.target.value })} /></label>
      <label>请求方法<select value={tool.request.method} onChange={event => update({ request: { ...tool.request, method: event.target.value }, retry: { ...tool.retry, maxRetries: event.target.value === 'GET' ? tool.retry.maxRetries : 0 } })}>{['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map(value => <option key={value}>{value}</option>)}</select></label>
      <label>请求地址<input type="url" value={tool.request.url ?? new URL(tool.request.path ?? '', tool.request.baseUrl).href} onChange={event => request({ url: event.target.value, baseUrl: undefined, path: undefined })} placeholder="https://example.com/items/{id}" /></label>
      <label>请求正文<select value={tool.request.contentType} onChange={event => request({ contentType: event.target.value })}>{['json', 'form', 'text'].map(value => <option key={value}>{value}</option>)}</select></label>
      <label>超时（毫秒）<input type="number" min={250} max={30000} value={tool.timeoutMs} onChange={event => update({ timeoutMs: Number(event.target.value) })} /></label>
      <label>响应格式<select value={tool.response.format} onChange={event => update({ response: { ...tool.response, format: event.target.value } })}>{['auto', 'json', 'text'].map(value => <option key={value}>{value}</option>)}</select></label>
      <label>提取响应字段<input value={tool.response.dataPath ?? ''} onChange={event => update({ response: { ...tool.response, dataPath: event.target.value || undefined } })} placeholder="如 data.items" /></label>
      <label>认证<select value={tool.request.auth.type} onChange={event => request({ auth: { type: event.target.value, ...(event.target.value === 'basic' ? { usernameCredentialSlot: 'username', passwordCredentialSlot: 'password' } : event.target.value !== 'none' ? { credentialSlot: 'token', ...(event.target.value === 'api_key' ? { placement: 'header', name: 'X-API-Key' } : {}) } : {}) } })}>{['none', 'bearer', 'basic', 'api_key'].map(value => <option key={value}>{value}</option>)}</select></label>
      {tool.request.auth.credentialSlot !== undefined && <label>凭据名称<input value={tool.request.auth.credentialSlot} onChange={event => auth({ credentialSlot: event.target.value })} /></label>}
      {tool.request.auth.type === 'basic' && <><label>用户名凭据名称<input value={tool.request.auth.usernameCredentialSlot} onChange={event => auth({ usernameCredentialSlot: event.target.value })} /></label><label>密码凭据名称<input value={tool.request.auth.passwordCredentialSlot} onChange={event => auth({ passwordCredentialSlot: event.target.value })} /></label></>}
      {tool.request.auth.type === 'api_key' && <><label>凭据位置<select value={tool.request.auth.placement} onChange={event => auth({ placement: event.target.value })}><option value="header">请求头</option><option value="query">查询参数</option></select></label><label>字段名称<input value={tool.request.auth.name} onChange={event => auth({ name: event.target.value })} /></label></>}
    </fieldset>
    <details><summary>请求头与重试</summary><fieldset disabled={busy}><label>操作类型<select value={tool.riskLevel} onChange={event => update({ riskLevel: event.target.value })}><option value="safe">安全读取</option><option value="read">读取</option><option value="write">写入</option><option value="dangerous">高影响操作</option></select></label>{Object.entries(tool.request.headers).map(([name, value]) => <div className="zz-cap-toolbar" key={name}><label>{name}<input value={value} onChange={event => request({ headers: { ...tool.request.headers, [name]: event.target.value } })} /></label><button onClick={() => request({ headers: Object.fromEntries(Object.entries(tool.request.headers).filter(([key]) => key !== name)) })}>移除请求头</button></div>)}<form className="zz-cap-toolbar" onSubmit={event => { event.preventDefault(); const form = event.currentTarget, name = form.elements.headerName.value.trim(); if (name) request({ headers: { ...tool.request.headers, [name]: form.elements.headerValue.value } }); form.reset() }}><input required name="headerName" aria-label="请求头名称" placeholder="Accept" /><input name="headerValue" aria-label="请求头值" placeholder="application/json" /><button>添加请求头</button></form>{tool.request.method === 'GET' && <><label>重试次数<input type="number" min={0} max={2} value={tool.retry.maxRetries} onChange={event => update({ retry: { ...tool.retry, maxRetries: Number(event.target.value) } })} /></label><label>重试间隔（毫秒）<input type="number" min={0} max={2000} value={tool.retry.backoffMs} onChange={event => update({ retry: { ...tool.retry, backoffMs: Number(event.target.value) } })} /></label></>}</fieldset></details>
    <fieldset disabled={busy}><legend>输入参数</legend>{Object.entries(tool.inputSchema.properties).map(([name, spec]) => <div className="zz-cap-toolbar" key={name}><label>{name}<select value={spec.type} onChange={event => parameter(name, { type: event.target.value, items: event.target.value === 'array' ? { type: 'string' } : undefined, properties: undefined, required: undefined, additionalProperties: undefined })}>{['string', 'number', 'integer', 'boolean', 'object', 'array'].map(value => <option key={value}>{value}</option>)}</select></label><label>说明<input value={spec.description ?? ''} onChange={event => parameter(name, { description: event.target.value })} /></label><label>发送字段名<input value={tool.request.parameters[name]?.name ?? name} onChange={event => request({ parameters: { ...tool.request.parameters, [name]: { location: tool.request.parameters[name]?.location ?? (tool.request.method === 'GET' ? 'query' : 'body'), name: event.target.value } } })} /></label><label>发送位置<select value={tool.request.parameters[name]?.location ?? (tool.request.method === 'GET' ? 'query' : 'body')} onChange={event => request({ parameters: { ...tool.request.parameters, [name]: { ...tool.request.parameters[name], location: event.target.value } } })}>{['query', 'path', 'header', 'body'].map(value => <option key={value}>{value}</option>)}</select></label><label><input type="checkbox" checked={tool.inputSchema.required?.includes(name) ?? false} onChange={event => update({ inputSchema: { ...tool.inputSchema, required: event.target.checked ? [...(tool.inputSchema.required ?? []), name] : tool.inputSchema.required.filter(value => value !== name) } })} />必填</label><button onClick={() => update({ inputSchema: { ...tool.inputSchema, properties: Object.fromEntries(Object.entries(tool.inputSchema.properties).filter(([key]) => key !== name)), required: tool.inputSchema.required?.filter(key => key !== name) }, request: { ...tool.request, parameters: Object.fromEntries(Object.entries(tool.request.parameters).filter(([key]) => key !== name)) } })}>移除</button></div>)}<form className="zz-cap-toolbar" onSubmit={event => { event.preventDefault(); const form = event.currentTarget, name = form.elements.parameterName.value.trim(); if (name && !tool.inputSchema.properties[name]) parameter(name, { type: 'string' }); form.reset() }}><input name="parameterName" aria-label="新参数名称" required pattern="[A-Za-z_][A-Za-z0-9_-]*" placeholder="输入新参数名称" /><button>添加参数</button></form></fieldset>
    <details><summary>测试当前工具</summary><p>将按当前填写的地址和方法发送真实请求。</p><fieldset disabled={busy} className="zz-cap-form-grid">{Object.entries(tool.inputSchema.properties).map(([name, spec]) => <label key={name}>{name}<input value={argumentsValue[name] ?? ''} onChange={event => setArguments(current => ({ ...current, [name]: event.target.value }))} placeholder={spec.type === 'object' || spec.type === 'array' ? 'JSON 值' : spec.type} /></label>)}{slots.map(name => <label key={name}>{name}<input type="password" autoComplete="off" value={credentials[name] ?? ''} onChange={event => setCredentials(current => ({ ...current, [name]: event.target.value }))} /></label>)}</fieldset><button disabled={busy} onClick={() => run(async () => { const args = Object.fromEntries(Object.entries(argumentsValue).filter(([, value]) => value !== '').map(([name, value]) => [name, tool.inputSchema.properties[name].type === 'string' ? value : JSON.parse(value)])); setResult(await api('store/testAdapter', { adapter, toolName: tool.name, arguments: args, credentials })) })}>发送测试请求</button>{result && <pre>{result.durationMs} ms{'\n'}{result.content.map(item => item.text).join('\n').slice(0, 16000)}</pre>}</details>
    <div className="zz-cap-toolbar"><button disabled={busy} onClick={() => run(async () => { await api('store/saveAdapter', { id: asset.id, version: version.version, etag, adapter }); saved() })}>保存 HTTP 工具</button>{adapter.tools.length > 1 && <button disabled={busy} onClick={() => { setAdapter(current => ({ ...current, tools: current.tools.filter((_, position) => position !== index) })); setIndex(0) }}>删除当前工具</button>}</div>
  </>}</section>
}
