import {
  agentServiceToken, contextServiceToken, scheduleServiceToken, sessionStoreToken, text, toolServiceToken,
  type AgentExecution, type AgentService, type CreateScheduleRequest, type JsonObject, type JsonValue,
  type ModelRef, type ScheduleRecord, type ScheduleService, type SealHarnessEvents, type SessionEvent,
  type SessionId, type SessionSnapshot, type SessionStore, type ToolDefinition,
} from "@seal-harness/core";
import { definePlugin } from "@seal-harness/kernel";

export const MIN_EVERY_INTERVAL_SECONDS = 300;
const MAX_TIMER_DELAY_MS = 2_147_483_647;
type Timer = ReturnType<typeof setTimeout>;
interface ActiveState { readonly records: ScheduleRecord[]; readonly nextId: number }

export interface ScheduleToolsConfig { readonly now?: () => number; readonly minimumEverySeconds?: number }

export class DurableScheduleService implements ScheduleService {
  readonly #timers = new Map<SessionId, Timer>(); readonly #running = new Map<SessionId, AgentExecution>(); readonly #queues = new Map<SessionId, Promise<void>>(); #closed = false;
  constructor(readonly sessions: SessionStore, readonly agents: AgentService, readonly now: () => number = Date.now, readonly minimumEverySeconds = MIN_EVERY_INTERVAL_SECONDS) { positive(minimumEverySeconds, "minimumEverySeconds"); }

  async start(): Promise<void> { for (const session of await this.sessions.list()) if (isRoot(session)) await this.reconcile(session.id); }
  async create(request: CreateScheduleRequest): Promise<ScheduleRecord> {
    return this.serial(request.sessionId, async () => {
      const session = await rootSession(this.sessions, request.sessionId); const state = fold(session); const prompt = cleanPrompt(request.prompt); const now = this.now(); let record: ScheduleRecord;
      if ("afterSeconds" in request) { const seconds = positive(request.afterSeconds, "after_seconds"); record = { id: `schedule-${state.nextId}`, sessionId: request.sessionId, kind: "after", prompt, scheduledAt: iso(now + seconds * 1000) }; }
      else if ("everySeconds" in request) { const seconds = positive(request.everySeconds, "every_seconds"); if (seconds < this.minimumEverySeconds) throw new Error(`every_seconds must be at least ${this.minimumEverySeconds}`); record = { id: `schedule-${state.nextId}`, sessionId: request.sessionId, kind: "every", prompt, scheduledAt: iso(now + seconds * 1000), intervalSeconds: seconds }; }
      else { const target = absoluteTime(request.at); if (target <= now) throw new Error("at must be in the future"); record = { id: `schedule-${state.nextId}`, sessionId: request.sessionId, kind: "at", prompt, scheduledAt: iso(target) }; }
      await append(this.sessions, request.sessionId, createEvent(record)); await this.reconcile(request.sessionId); return record;
    });
  }
  async list(sessionId: SessionId): Promise<readonly ScheduleRecord[]> { return fold(await rootSession(this.sessions, sessionId)).records; }
  async delete(sessionId: SessionId, id: string): Promise<boolean> { return this.serial(sessionId, async () => { const session = await rootSession(this.sessions, sessionId); if (!fold(session).records.some(value => value.id === id)) return false; await append(this.sessions, sessionId, { type: "schedule.changed", payload: { version: 1, operation: "delete", id } }); await this.reconcile(sessionId); return true; }); }
  /** Immediately evaluate due work; exposed for embedders and deterministic clocks. */
  driveDue(sessionId: SessionId): Promise<void> { return this.serial(sessionId, () => this.dispatch(sessionId)); }
  async dispose(): Promise<void> { this.#closed = true; for (const timer of this.#timers.values()) clearTimeout(timer); this.#timers.clear(); for (const execution of this.#running.values()) execution.abort(new Error("Schedule service stopped")); await Promise.allSettled([...this.#running.values()].map(value => value.result)); await Promise.allSettled([...this.#queues.values()]); }

  private async reconcile(id: SessionId): Promise<void> {
    const prior = this.#timers.get(id); if (prior !== undefined) clearTimeout(prior); this.#timers.delete(id); if (this.#closed || this.#running.has(id)) return;
    const session = await this.sessions.read(id); if (session === undefined || !isRoot(session)) return; const records = fold(session).records; if (records.length === 0) return;
    const target = Math.min(...records.map(value => Date.parse(value.scheduledAt))); const delay = Math.max(0, Math.min(target - this.now(), MAX_TIMER_DELAY_MS)); const timer = setTimeout(() => { this.#timers.delete(id); void this.serial(id, () => this.dispatch(id)).catch(() => { void this.reconcile(id); }); }, delay); this.#timers.set(id, timer);
  }
  private async dispatch(id: SessionId): Promise<void> {
    if (this.#closed || this.#running.has(id)) return; const session = await rootSession(this.sessions, id); const state = fold(session); const now = this.now(); const due = state.records.filter(value => Date.parse(value.scheduledAt) <= now).sort((a, b) => Date.parse(a.scheduledAt) - Date.parse(b.scheduledAt)); if (due.length === 0) { await this.reconcile(id); return; }
    const selected = due[0]!.kind === "every" ? due.filter(value => value.kind === "every") : [due[0]!]; const acceptedAt = iso(now); const preludeEvents = selected.map(record => dispatchEvent(record, acceptedAt)); const route = latestRoute(session); const framing = selected.length === 1 ? `[Scheduled reminder ${selected[0]!.id} due ${selected[0]!.scheduledAt}]\n${selected[0]!.prompt}` : `[Scheduled recurring reminders due]\n${selected.map(value => `- ${value.id} (${value.scheduledAt}): ${value.prompt}`).join("\n")}`;
    let execution: AgentExecution;
    try { execution = await this.agents.prompt({ sessionId: id, cwd: cwd(session), model: route.model, prompt: [text(framing)], preludeEvents, ...(route.reasoning === undefined ? {} : { reasoning: route.reasoning }) }); }
    catch (error) { await this.reconcile(id); throw error; }
    this.#running.set(id, execution); void execution.result.finally(() => { if (this.#running.get(id) === execution) this.#running.delete(id); void this.reconcile(id); });
  }
  private serial<T>(id: SessionId, operation: () => Promise<T>): Promise<T> { const previous = this.#queues.get(id) ?? Promise.resolve(); const result = previous.catch(() => undefined).then(operation); const tail = result.then(() => undefined, () => undefined); this.#queues.set(id, tail); void tail.finally(() => { if (this.#queues.get(id) === tail) this.#queues.delete(id); }); return result; }
}

export const scheduleToolsPlugin = definePlugin<ScheduleToolsConfig, SealHarnessEvents>({
  name: "schedule-tools", provides: [scheduleServiceToken], requires: [agentServiceToken, sessionStoreToken, toolServiceToken, contextServiceToken],
  async setup(context, config) {
    const service = new DurableScheduleService(context.use(sessionStoreToken), context.use(agentServiceToken), config.now ?? Date.now, config.minimumEverySeconds ?? MIN_EVERY_INTERVAL_SECONDS); context.provide(scheduleServiceToken, service);
    for (const tool of scheduleTools(service, service.minimumEverySeconds)) context.effect(context.use(toolServiceToken).register(tool));
    context.effect(context.use(contextServiceToken).register({ name: "schedule-guidance", async contribute() { return { systemPrompt: "Use schedule_create for reminders requested by the user. Use schedule_list to inspect active reminders and schedule_delete to remove one. Recurring reminders have a minimum five-minute interval." }; } }));
    await service.start(); context.effect(() => service.dispose());
  },
});

export function scheduleTools(service: ScheduleService, minimumEverySeconds = MIN_EVERY_INTERVAL_SECONDS): ToolDefinition[] { return [
  { name: "schedule_create", description: "Create one durable reminder using exactly one of after_seconds, every_seconds, or at.", inputSchema: object({ prompt: string(), after_seconds: { type: "integer", minimum: 1 }, every_seconds: { type: "integer", minimum: minimumEverySeconds }, at: { oneOf: [{ type: "string" }, { type: "object", additionalProperties: false, required: ["date", "time", "time_zone"], properties: { date: string(), time: string(), time_zone: string() } }] } }, ["prompt"]), classify: (_input, ctx) => action("schedule_create", "Create reminder", ctx.cwd, "workspace-write"), async execute(input, ctx) { const choices = [input.after_seconds, input.every_seconds, input.at].filter(value => value !== undefined); if (choices.length !== 1) throw new Error("exactly one of after_seconds, every_seconds, or at is required"); const base = { sessionId: ctx.sessionId, prompt: requiredString(input.prompt, "prompt") }; const record = input.after_seconds !== undefined ? await service.create({ ...base, afterSeconds: input.after_seconds as number }) : input.every_seconds !== undefined ? await service.create({ ...base, everySeconds: input.every_seconds as number }) : await service.create({ ...base, at: atInput(input.at) }); return output(scheduleJson(record)); } },
  { name: "schedule_list", description: "List active durable reminders for this Session.", inputSchema: object({}), classify: (_input, ctx) => action("schedule_list", "List reminders", ctx.cwd), async execute(_input, ctx) { return output((await service.list(ctx.sessionId)).map(scheduleJson)); } },
  { name: "schedule_delete", description: "Delete one active reminder by id.", inputSchema: object({ id: string() }, ["id"]), classify: (_input, ctx) => action("schedule_delete", "Delete reminder", ctx.cwd, "workspace-write"), async execute(input, ctx) { const id = requiredString(input.id, "id"); return output({ id, deleted: await service.delete(ctx.sessionId, id) }); } },
]; }

function fold(session: SessionSnapshot): ActiveState { const records = new Map<string, ScheduleRecord>(); let highest = 0; for (const item of session.events) { if (item.event.type !== "schedule.changed" || item.event.payload.version !== 1) continue; const change = item.event.payload; const match = /^schedule-(\d+)$/u.exec(change.id); if (match !== null) highest = Math.max(highest, Number(match[1])); if (change.operation === "create" && change.record !== undefined) records.set(change.id, { id: change.id, sessionId: session.id, ...change.record }); else if (change.operation === "delete") records.delete(change.id); else if (change.operation === "dispatch") { const current = records.get(change.id); if (current?.kind === "every" && current.intervalSeconds !== undefined) records.set(change.id, { ...current, scheduledAt: nextOccurrence(current.scheduledAt, current.intervalSeconds, change.acceptedAt ?? item.timestamp) }); else records.delete(change.id); } } return { records: [...records.values()].sort((a, b) => Date.parse(a.scheduledAt) - Date.parse(b.scheduledAt) || a.id.localeCompare(b.id)), nextId: highest + 1 }; }
function nextOccurrence(anchor: string, seconds: number, acceptedAt: string): string { const step = seconds * 1000; const start = Date.parse(anchor); const accepted = Date.parse(acceptedAt); return iso(start + (Math.floor(Math.max(0, accepted - start) / step) + 1) * step); }
function createEvent(record: ScheduleRecord): SessionEvent { return { type: "schedule.changed", payload: { version: 1, operation: "create", id: record.id, record: { kind: record.kind, prompt: record.prompt, scheduledAt: record.scheduledAt, ...(record.intervalSeconds === undefined ? {} : { intervalSeconds: record.intervalSeconds }) } } }; }
function dispatchEvent(record: ScheduleRecord, acceptedAt: string): SessionEvent { return { type: "schedule.changed", payload: { version: 1, operation: "dispatch", id: record.id, ...(record.kind === "every" ? { acceptedAt } : {}) } }; }
async function append(store: SessionStore, id: SessionId, event: SessionEvent): Promise<void> { for (let attempt = 0; attempt < 8; attempt += 1) { const session = await rootSession(store, id); try { await store.append({ id, expectedVersion: session.version, events: [event] }); return; } catch (error) { if (attempt === 7 || !(error instanceof Error) || error.name !== "SessionConflictError") throw error; } } }
async function rootSession(store: SessionStore, id: SessionId): Promise<SessionSnapshot> { const session = await store.read(id); if (session === undefined || !isRoot(session)) throw new Error(`root Session not found: ${id}`); return session; }
function isRoot(session: SessionSnapshot): boolean { const created = session.events.find(value => value.event.type === "session.created"); return created?.event.type === "session.created" && typeof created.event.payload.metadata?.["sealHarness.parentSessionId"] !== "string"; }
function cwd(session: SessionSnapshot): string { const created = session.events.find(value => value.event.type === "session.created"); if (created?.event.type !== "session.created") throw new Error("Session has no creation event"); return created.event.payload.cwd; }
function latestRoute(session: SessionSnapshot): { model: ModelRef; reasoning?: "off" | "low" | "medium" | "high" | "max" } { const event = session.events.slice().reverse().find(value => value.event.type === "run.started"); if (event?.event.type !== "run.started") throw new Error(`Session has no model route: ${session.id}`); return { model: event.event.payload.model, ...(event.event.payload.reasoning === undefined ? {} : { reasoning: event.event.payload.reasoning }) }; }
function absoluteTime(value: string | { date: string; time: string; timeZone: string }): number { if (typeof value === "string") { const match = /^(\d{4})-(\d\d)-(\d\d)T(\d\d):(\d\d)(?::(\d\d)(?:\.(\d{1,9}))?)?(Z|([+-])(\d\d):(\d\d))$/u.exec(value); if (match === null) throw new Error("at must be strict offset RFC 3339"); validateDateTime(Number(match[1]), Number(match[2]), Number(match[3]), Number(match[4]), Number(match[5]), Number(match[6] ?? 0)); if (Number(match[10] ?? 0) > 23 || Number(match[11] ?? 0) > 59) throw new Error("at has an invalid numeric offset"); const parsed = Date.parse(value); if (!Number.isFinite(parsed)) throw new Error("at is not a valid instant"); return parsed; } return zonedTime(value.date, value.time, value.timeZone); }
function zonedTime(date: string, time: string, zone: string): number { const match = /^(\d{4})-(\d\d)-(\d\d)$/.exec(date); const clock = /^(\d\d):(\d\d)(?::(\d\d)(?:\.(\d{1,9}))?)?$/.exec(time); if (match === null || clock === null) throw new Error("local at date/time is invalid"); const parts = [match[1], match[2], match[3], clock[1], clock[2], clock[3] ?? "00"].map(Number); validateDateTime(parts[0]!, parts[1]!, parts[2]!, parts[3]!, parts[4]!, parts[5]!); if (zone !== "UTC" && !/^[A-Za-z_+-]+(?:\/[A-Za-z0-9_+-]+)+$/u.test(zone)) throw new Error("time_zone must be UTC or a valid IANA Area/Location name"); const milliseconds = Number((clock[4] ?? "").padEnd(3, "0").slice(0, 3)); const desired = Date.UTC(parts[0]!, parts[1]! - 1, parts[2]!, parts[3]!, parts[4]!, parts[5]!, milliseconds); let formatter: Intl.DateTimeFormat; try { formatter = new Intl.DateTimeFormat("en-CA", { timeZone: zone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" }); } catch { throw new Error("time_zone must be UTC or a valid IANA Area/Location name"); } let candidate = desired; for (let count = 0; count < 4; count += 1) { const shown = localEpoch(formatter, candidate) + milliseconds; candidate += desired - shown; } if (localEpoch(formatter, candidate) + milliseconds !== desired) throw new Error("local date/time does not exist in time_zone"); const overlaps: number[] = []; for (let minutes = -180; minutes <= 180; minutes += 15) { const alternative = candidate + minutes * 60_000; if (localEpoch(formatter, alternative) + milliseconds === desired) overlaps.push(alternative); } return Math.min(...overlaps); }
function localEpoch(formatter: Intl.DateTimeFormat, instant: number): number { const values = Object.fromEntries(formatter.formatToParts(instant).filter(value => value.type !== "literal").map(value => [value.type, Number(value.value)])); return Date.UTC(values.year!, values.month! - 1, values.day!, values.hour!, values.minute!, values.second!); }
function validateDateTime(year: number, month: number, day: number, hour: number, minute: number, second: number): void { const candidate = new Date(Date.UTC(year, month - 1, day, hour, minute, second)); if (candidate.getUTCFullYear() !== year || candidate.getUTCMonth() !== month - 1 || candidate.getUTCDate() !== day || hour > 23 || minute > 59 || second > 59) throw new Error("date/time is invalid"); }
function atInput(value: JsonValue | undefined): string | { date: string; time: string; timeZone: string } { if (typeof value === "string") return value; if (!jsonObject(value)) throw new Error("at is invalid"); return { date: requiredString(value.date, "date"), time: requiredString(value.time, "time"), timeZone: requiredString(value.time_zone, "time_zone") }; }
function scheduleJson(value: ScheduleRecord): JsonObject { return { id: value.id, sessionId: value.sessionId, kind: value.kind, prompt: value.prompt, scheduledAt: value.scheduledAt, ...(value.intervalSeconds === undefined ? {} : { intervalSeconds: value.intervalSeconds }) }; }
function jsonObject(value: JsonValue | undefined): value is JsonObject { return typeof value === "object" && value !== null && !Array.isArray(value); }
function output(value: JsonValue) { return { content: [text(JSON.stringify(value))], details: value }; }
function action(toolName: string, summary: string, target: string, risk: "read" | "workspace-write" = "read") { return { kind: "tool" as const, toolName, risk, summary, target }; }
function object(properties: JsonObject, required: readonly string[] = []): JsonObject { return { type: "object", additionalProperties: false, properties, required }; }
function string(): JsonObject { return { type: "string", minLength: 1 }; }
function requiredString(value: JsonValue | undefined, name: string): string { if (typeof value !== "string" || !value.trim()) throw new Error(`${name} must be non-empty`); return value.trim(); }
function cleanPrompt(value: string): string { return requiredString(value, "prompt"); }
function positive(value: number, name: string): number { if (!Number.isSafeInteger(value) || value < 1) throw new Error(`${name} must be a positive safe integer`); return value; }
function iso(value: number): string { if (!Number.isFinite(value)) throw new Error("schedule target is outside the supported date range"); return new Date(value).toISOString(); }
