import { commandServiceToken, permissionPresetServiceToken, sessionInitializerToken, sessionStoreToken, SessionConflictError, type CommandService, type PermissionPresetOption, type PermissionPresetService, type PermissionPresetSpec, type PermissionSelect, type SealHarnessEvents, type SessionEvent, type SessionId, type SessionSnapshot, type SessionStore } from "@seal-harness/core";
import { definePlugin } from "@seal-harness/kernel";

export const CUSTOM_PRESET = "custom";
export interface PermissionPresetsConfig { readonly presets?: Readonly<Record<string, PermissionPresetSpec>>; readonly defaultPreset?: string }
const DEFAULTS: Readonly<Record<string, PermissionPresetSpec>> = Object.freeze({
  "workspace-write": { sandbox: "workspace-write", approval: "ask", name: "workspace-write", description: "Write inside the workspace; external and dangerous actions require approval." },
  "danger-full-access": { sandbox: "danger-full-access", approval: "never", name: "danger-full-access", description: "Full file access without approval prompts." },
});

export class DurablePermissionPresetService implements PermissionPresetService {
  readonly presets: Readonly<Record<string, PermissionPresetSpec>>; readonly names: readonly string[]; readonly defaultPreset: string; readonly #queues = new Map<SessionId, Promise<void>>(); readonly #effective = new Map<SessionId, PermissionPresetSpec>();
  constructor(readonly sessions: SessionStore, config: PermissionPresetsConfig = {}) {
    this.presets = config.presets ?? DEFAULTS; this.names = Object.keys(this.presets);
    if (this.names.length === 0) throw new TypeError("permission preset table must not be empty");
    if (CUSTOM_PRESET in this.presets) throw new TypeError(`permission preset name ${CUSTOM_PRESET} is reserved`);
    this.defaultPreset = config.defaultPreset ?? this.#derive({ preset: null, sandbox: null, approval: null });
    if (this.defaultPreset === CUSTOM_PRESET) throw new TypeError("permission defaults match no preset; configure defaultPreset"); this.resolve(this.defaultPreset);
  }
  resolve(name: string): PermissionPresetSpec { const value = this.presets[name]; if (value === undefined) throw new Error(`unknown permission preset "${name}" (known: ${this.names.join(", ")})`); return value; }
  async current(sessionId: SessionId): Promise<string> { const name = this.#derive(fold(await requiredSession(this.sessions, sessionId))); if (name !== CUSTOM_PRESET) this.#effective.set(sessionId, this.resolve(name)); return name; }
  sandboxMode(sessionId: SessionId): PermissionPresetSpec["sandbox"] { return this.#effective.get(sessionId)?.sandbox ?? this.resolve(this.defaultPreset).sandbox; }
  async select(sessionId: SessionId): Promise<PermissionSelect> { const currentValue = await this.current(sessionId); return { options: [...this.names.map((name) => this.#option(name)), ...(currentValue === CUSTOM_PRESET ? [this.#option(CUSTOM_PRESET)] : [])], currentValue }; }
  set(sessionId: SessionId, name: string): Promise<string> { return this.#serial(sessionId, async () => { const snapshot = await requiredSession(this.sessions, sessionId); const next = await this.#apply(snapshot, name); const current = this.#derive(fold(next)); this.#effective.set(sessionId, this.resolve(current)); return current; }); }
  initialize(session: SessionSnapshot): Promise<SessionSnapshot> { return this.#serial(session.id, async () => { const latest = await requiredSession(this.sessions, session.id); const state = fold(latest); if (state.preset !== null && state.sandbox !== null && state.approval !== null) return latest; const selected = state.preset ?? (state.sandbox === null && state.approval === null ? this.defaultPreset : this.#derive(state)); const preset = selected === CUSTOM_PRESET ? undefined : this.resolve(selected); const events: SessionEvent[] = [
      ...(state.preset === null && preset !== undefined ? [{ type: "permission.preset" as const, payload: { preset: selected } }] : []),
      ...(state.sandbox === null ? [{ type: "sandbox.mode" as const, payload: { mode: preset?.sandbox ?? "workspace-write" } }] : []),
      ...(state.approval === null ? [{ type: "approval.policy" as const, payload: { policy: preset?.approval ?? "ask" } }] : []),
    ]; const initialized = events.length === 0 ? latest : await this.#append(latest, events); const current = this.#derive(fold(initialized)); if (current !== CUSTOM_PRESET) this.#effective.set(session.id, this.resolve(current)); return initialized; }); }
  async #apply(snapshot: SessionSnapshot, name: string): Promise<SessionSnapshot> { const spec = this.resolve(name); const state = fold(snapshot); if (this.#derive(state) === name) return snapshot; return this.#append(snapshot, [
    { type: "permission.preset", payload: { preset: name } },
    ...(state.sandbox === spec.sandbox ? [] : [{ type: "sandbox.mode" as const, payload: { mode: spec.sandbox } }]),
    ...(state.approval === spec.approval ? [] : [{ type: "approval.policy" as const, payload: { policy: spec.approval } }]),
  ]); }
  async #append(snapshot: SessionSnapshot, events: readonly SessionEvent[]): Promise<SessionSnapshot> { try { return await this.sessions.append({ id: snapshot.id, expectedVersion: snapshot.version, events }); } catch (error) { if (!(error instanceof SessionConflictError)) throw error; const latest = await requiredSession(this.sessions, snapshot.id); return this.sessions.append({ id: latest.id, expectedVersion: latest.version, events }); } }
  #derive(state: ReturnType<typeof fold>): string { const sandbox = state.sandbox ?? "workspace-write"; const approval = state.approval ?? "ask"; if (state.preset !== null) { const spec = this.presets[state.preset]; if (spec?.sandbox === sandbox && spec.approval === approval) return state.preset; } return this.names.find((name) => this.presets[name]?.sandbox === sandbox && this.presets[name]?.approval === approval) ?? CUSTOM_PRESET; }
  #option(name: string): PermissionPresetOption { if (name === CUSTOM_PRESET) return { value: name, name: "Custom", description: "Current sandbox and approval settings do not match a preset." }; const spec = this.resolve(name); return { value: name, name: spec.name ?? name, ...(spec.description === undefined ? {} : { description: spec.description }) }; }
  #serial<T>(id: SessionId, work: () => Promise<T>): Promise<T> { const previous = this.#queues.get(id) ?? Promise.resolve(); const result = previous.catch(() => undefined).then(work); const tail = result.then(() => undefined, () => undefined); this.#queues.set(id, tail); return result.finally(() => { if (this.#queues.get(id) === tail) this.#queues.delete(id); }); }
}
function fold(session: SessionSnapshot): { preset: string | null; sandbox: PermissionPresetSpec["sandbox"] | null; approval: PermissionPresetSpec["approval"] | null } { let preset = null as string | null; let sandbox = null as PermissionPresetSpec["sandbox"] | null; let approval = null as PermissionPresetSpec["approval"] | null; for (const entry of session.events) { if (entry.event.type === "permission.preset") preset = entry.event.payload.preset; else if (entry.event.type === "sandbox.mode") sandbox = entry.event.payload.mode; else if (entry.event.type === "approval.policy") approval = entry.event.payload.policy; } return { preset, sandbox, approval }; }
async function requiredSession(store: SessionStore, id: SessionId): Promise<SessionSnapshot> { const value = await store.read(id); if (value === undefined) throw new Error(`Session not found: ${id}`); return value; }
function registerCommand(commands: CommandService, service: PermissionPresetService): () => void { return commands.register({ name: "permission", description: "Switch the permission preset", input: { hint: "<preset>" }, async handler({ sessionId, rawInput }) { const name = rawInput.trim(); if (name === "") return { kind: "success", text: `current preset ${await service.current(sessionId)} (available: ${service.names.join(", ")})` }; try { return { kind: "success", text: `preset ${await service.set(sessionId, name)}` }; } catch (error) { return { kind: "error", text: error instanceof Error ? error.message : String(error) }; } } }); }
export const permissionPresetsPlugin = definePlugin<PermissionPresetsConfig, SealHarnessEvents>({ name: "permission-presets", provides: [permissionPresetServiceToken, sessionInitializerToken], requires: [sessionStoreToken], optional: [commandServiceToken], setup(context, config) { const service = new DurablePermissionPresetService(context.use(sessionStoreToken), config); context.provide(permissionPresetServiceToken, service); context.provide(sessionInitializerToken, service); if (context.has(commandServiceToken)) context.effect(registerCommand(context.use(commandServiceToken), service)); } });
