// 来源：Stratex LocalWorkflowPanel.vue；只呈现现有本机流程协议支持的管理入口。
import React, { useState } from 'react'
import { Icon } from '../../capability-shared/src/icons.jsx'
import { IconButton, statuses, transitioning } from './instance-card.jsx'
import { WorkflowResources } from './resource-picker.jsx'

export function WorkflowDetail({ api, instance, instances, busy, error, onSelect, onBack, onAction, onDelete, onRefresh }) {
  const [copied, setCopied] = useState(''), [copyError, setCopyError] = useState(''), [shareIndex, setShareIndex] = useState(0)
  const running = instance.status === 'ready', disabled = busy || transitioning(instance.status)
  const chatUrl = instance.adminUrl ? new URL('/chat', instance.adminUrl).href : ''
  const shareOrigin = instance.shareUrls?.[shareIndex] ?? instance.shareUrls?.[0]
  const copy = async value => { try { await navigator.clipboard.writeText(value); setCopied(value); setCopyError('') } catch { setCopyError('复制失败，请选中地址手动复制。') } }
  const open = target => onAction(instance, target === 'admin' ? 'open' : target)
  return <div className="za-detail"><header className="feature-page-header"><div className="feature-page-header__heading"><IconButton label="返回智能体" icon="back" className="feature-page-header__back" onClick={onBack} /><div className="feature-page-header__copy"><h1>流程型智能体</h1><p>管理你的智能能力实例</p></div></div></header><div className="agent-local-ui"><section className="local-agent" aria-busy={busy}>
    <header className="local-heading"><div><span className="eyebrow">本机发布 · 内网共享</span><h2>我的流程型智能体</h2><p>管理本机实例，进入管理页面配置流程。</p></div><button disabled={busy} onClick={onRefresh}>刷新状态</button></header>
    {(error || copyError) && <p role="alert" className="error">{error || copyError}</p>}
    <nav className="instance-selector" aria-label="已发布的流程智能体"><label>当前实例<select value={instance.id} disabled={busy} onChange={event => { onSelect(instances.find(item => item.id === event.target.value)); setShareIndex(0); setCopied(''); setCopyError('') }}>{instances.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="instance-lifecycle"><button disabled={disabled || !running} onClick={() => onAction(instance, 'restart')}>重启</button><button className="danger-button" disabled={disabled || !running} onClick={() => onAction(instance, 'stop')}>停止</button></div><IconButton className="icon-action danger" label="删除实例" icon="delete" disabled={disabled} onClick={() => onDelete(instance)} /><span className="help">本机端口 {instance.port ?? '—'}</span><p className="instance-note">流程版本与对话历史保存在本机，停止或重启会保留。</p></nav>
    <section className="instance-overview"><div className="overview-top"><div className="instance-identity"><span className="instance-icon"><Icon name="automation" size={28} /></span><h3>{instance.name}</h3></div><span className={`status-badge${running ? ' ready' : ''}`}>{statuses[instance.status]}</span></div><p>{running ? '运行环境已就绪，流程编辑与发布请在管理页面完成。' : instance.statusReason || '实例尚未就绪，启动后可进入管理页面。'}</p><div className="actions"><button className="primary" disabled={disabled || !running} onClick={() => open('admin')}>打开管理页面<Icon name="external" size={16} /></button><button disabled={disabled || !running} onClick={() => open('chat')}>开始对话<Icon name="external" size={16} /></button>{!running && <button disabled={disabled} onClick={() => onAction(instance, 'start')}>启动运行环境</button>}</div></section>
    <div className="access-grid"><section className="access-card"><h3>访问地址</h3><p>按用途打开或复制地址。</p>{[['管理页面', instance.adminUrl], ['对话页面', chatUrl], ['API 接口', instance.apiUrl]].map(([label, url]) => <div className="address-row" key={label}><span>{label}</span><code>{url || '就绪后可用'}</code><button disabled={!url} aria-label={`复制${label}地址`} onClick={() => void copy(url)}>{url && copied === url ? '已复制' : '复制'}</button></div>)}<button className="text-button" disabled={disabled || !running} onClick={() => open('api')}>查看接口<Icon name="external" size={14} /></button></section>
    <section className="access-card"><h3>内网共享</h3>{shareOrigin ? <><p>通过内网地址访问。</p>{instance.shareUrls.length > 1 && <select aria-label="选择内网地址" value={shareIndex} onChange={event => setShareIndex(Number(event.target.value))}>{instance.shareUrls.map((url, index) => <option key={url} value={index}>{url}</option>)}</select>}{[['管理页面', '/admin/'], ['对话页面', '/chat'], ['调用接口', '/api/chat/stream']].map(([label, path]) => <div className="share-row" key={path}><span>{label}</span><code>{shareOrigin}{path}</code><button onClick={() => void copy(`${shareOrigin}${path}`)}>{copied === `${shareOrigin}${path}` ? '已复制' : '复制'}</button></div>)}</> : <><span className="status-badge">{instance.access === 'local' ? '仅限本机访问' : '暂无可用地址'}</span><p>{instance.access === 'local' ? '当前实例配置为仅在本机使用。' : '连接公司网络后刷新，即可查看可用的内网地址。'}</p><button disabled={busy} onClick={onRefresh}>重新检测</button></>}</section></div>
    <WorkflowResources key={instance.id} api={api} instance={instance} />
  </section></div></div>
}
