import { credentialServiceToken, WebError, webAccessServiceToken, type CredentialService, type SealHarnessEvents, type WebSearchProvider, type WebSearchRequest, type WebSearchResult } from "@seal-harness/core";
import { definePlugin } from "@seal-harness/kernel";
export interface ExaWebSearchConfig { readonly credentialProvider?: string; readonly credentialName?: string; readonly endpoint?: string; readonly timeoutMs?: number; readonly maxResponseBytes?: number }
export class ExaWebSearchProvider implements WebSearchProvider {
  readonly id = "exa"; readonly endpoint: string; readonly timeoutMs: number; readonly maxResponseBytes: number;
  constructor(readonly credentials: CredentialService, readonly config: ExaWebSearchConfig = {}, readonly request: typeof fetch = fetch) { this.endpoint = config.endpoint ?? "https://api.exa.ai/search"; const parsed = new URL(this.endpoint); if (parsed.protocol !== "https:" && parsed.hostname !== "127.0.0.1" && parsed.hostname !== "localhost") throw new Error("Exa endpoint must use HTTPS"); this.timeoutMs = positive(config.timeoutMs ?? 30_000); this.maxResponseBytes = positive(config.maxResponseBytes ?? 2_000_000); }
  available(): boolean { return true; }
  async search(input: WebSearchRequest, signal?: AbortSignal): Promise<WebSearchResult> { const combined = signal === undefined ? AbortSignal.timeout(this.timeoutMs) : AbortSignal.any([signal, AbortSignal.timeout(this.timeoutMs)]); const key = await this.credentials.resolve({ provider: this.config.credentialProvider ?? "exa", name: this.config.credentialName ?? "apiKey", signal: combined }); if (!key) throw new WebError("Exa API key is unavailable", "WEB_PROVIDER_CONFIGURED_UNAVAILABLE"); let response: Response; try { response = await this.request(this.endpoint, { method: "POST", redirect: "error", headers: { authorization: `Bearer ${key}`, "content-type": "application/json" }, body: JSON.stringify({ query: input.query, numResults: input.maxResults, contents: { text: { maxCharacters: 1000 } } }), signal: combined }); } catch (error) { throw new WebError(`Exa search failed: ${error instanceof Error ? error.message : String(error)}`, combined.aborted ? "WEB_ABORTED" : "WEB_PROVIDER_ERROR"); } if (!response.ok) throw new WebError(`Exa search returned HTTP ${response.status}`, "WEB_PROVIDER_ERROR"); const declared = Number(response.headers.get("content-length")); if (Number.isFinite(declared) && declared > this.maxResponseBytes) throw new WebError("Exa response is too large", "WEB_PROVIDER_ERROR"); const data = await response.arrayBuffer(); if (data.byteLength > this.maxResponseBytes) throw new WebError("Exa response is too large", "WEB_PROVIDER_ERROR"); let parsed: any; try { parsed = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(data)); } catch { throw new WebError("Exa returned malformed JSON", "WEB_PROVIDER_ERROR"); } if (!Array.isArray(parsed?.results)) throw new WebError("Exa returned a malformed result", "WEB_PROVIDER_ERROR"); const sources = parsed.results.map((item: any) => { if (typeof item?.url !== "string") throw new WebError("Exa returned a malformed source", "WEB_PROVIDER_ERROR"); const snippet = typeof item.text === "string" ? item.text : typeof item.highlights?.[0] === "string" ? item.highlights[0] : undefined; return { url: item.url, ...(typeof item.title === "string" ? { title: item.title } : {}), ...(snippet === undefined ? {} : { snippet }), ...(typeof item.publishedDate === "string" ? { publishedAt: item.publishedDate } : {}) }; }); return { sources }; }
}
function positive(value: number): number { if (!Number.isSafeInteger(value) || value < 1) throw new Error("Exa limits must be positive safe integers"); return value; }
export const exaWebSearchPlugin = definePlugin<ExaWebSearchConfig, SealHarnessEvents>({ name: "web-search-exa", requires: [webAccessServiceToken, credentialServiceToken], setup(context, config) { return context.use(webAccessServiceToken).registerSearchProvider(new ExaWebSearchProvider(context.use(credentialServiceToken), config)); } });
