import { UserQuestionError, userQuestionServiceToken, type AskUserQuestionAnswer, type AskUserQuestionRequest, type SealHarnessEvents, type UserQuestionAnswerer, type UserQuestionService } from "@seal-harness/core";
import { definePlugin } from "@seal-harness/kernel";
export interface UserQuestionsConfig { readonly answerer?: UserQuestionAnswerer }
export class DefaultUserQuestionService implements UserQuestionService {
  readonly #answerers: UserQuestionAnswerer[] = [];
  registerAnswerer(answerer: UserQuestionAnswerer): () => void { this.#answerers.push(answerer); let active = true; return () => { if (!active) return; active = false; const i = this.#answerers.indexOf(answerer); if (i >= 0) this.#answerers.splice(i, 1); }; }
  async ask(request: AskUserQuestionRequest): Promise<AskUserQuestionAnswer> {
    request.signal?.throwIfAborted(); validate(request); const snapshot = structuredClone({ sessionId: request.sessionId, questions: request.questions }) as AskUserQuestionRequest;
    for (const answerer of [...this.#answerers]) { request.signal?.throwIfAborted(); const answer = await withAbort(answerer({ ...snapshot, ...(request.signal === undefined ? {} : { signal: request.signal }) }), request.signal); if (answer !== undefined) return validateAnswer(snapshot, answer); }
    throw new UserQuestionError("no user-questions answerer accepted the request", "NO_PROVIDER");
  }
}
function validate(request: AskUserQuestionRequest): void { if (request.questions.length === 0) throw new UserQuestionError("ask_user_question requires at least one question", "EMPTY_QUESTIONS"); const ids = new Set<string>(); for (const q of request.questions) { if (q.id.trim() === "" || ids.has(q.id)) throw new UserQuestionError("question ids must be non-empty and unique", "INVALID_QUESTION"); ids.add(q.id); if (q.question.trim() === "") throw new UserQuestionError(`question ${q.id} text must be non-empty`, "INVALID_QUESTION"); if (q.options?.some((x) => x.label.trim() === "") || new Set(q.options?.map((x) => x.label)).size !== (q.options?.length ?? 0)) throw new UserQuestionError(`question ${q.id} option labels must be non-empty and unique`, "INVALID_QUESTION"); if (q.intent !== undefined && (!(q.options ?? []).some((x) => x.label === q.intent!.approve) || q.detail === undefined)) throw new UserQuestionError(`question ${q.id} has an invalid ${q.intent.kind} intent`, "BAD_INTENT"); } }
function validateAnswer(request: AskUserQuestionRequest, answer: AskUserQuestionAnswer): AskUserQuestionAnswer { const questions = new Map(request.questions.map((x) => [x.id, x])); if (answer.answers.length !== request.questions.length) throw new UserQuestionError("answer must cover every question exactly once", "INVALID_ANSWER"); const seen = new Set<string>(); const values = answer.answers.map((item) => { const q = questions.get(item.id); if (q === undefined || seen.has(item.id)) throw new UserQuestionError("answer contains an unknown or duplicate question id", "INVALID_ANSWER"); seen.add(item.id); if (!q.multiSelect && item.selected.length > 1) throw new UserQuestionError(`question ${item.id} is single-select`, "INVALID_ANSWER"); const labels = new Set(q.options?.map((x) => x.label)); if (item.selected.some((x) => !labels.has(x))) throw new UserQuestionError(`answer for ${item.id} selected an unknown option`, "INVALID_ANSWER"); if (item.selected.length === 0 && item.custom?.trim() === "") throw new UserQuestionError(`answer for ${item.id} is empty`, "INVALID_ANSWER"); return Object.freeze({ id: item.id, selected: Object.freeze([...item.selected]), ...(item.custom === undefined ? {} : { custom: item.custom }) }); }); return Object.freeze({ answers: Object.freeze(values) }); }
function withAbort<T>(promise: Promise<T>, signal?: AbortSignal): Promise<T> { if (signal === undefined) return promise; if (signal.aborted) return Promise.reject(signal.reason); return new Promise((resolve, reject) => { const abort = () => reject(signal.reason ?? new Error("question aborted")); signal.addEventListener("abort", abort, { once: true }); promise.then((x) => { signal.removeEventListener("abort", abort); resolve(x); }, (e) => { signal.removeEventListener("abort", abort); reject(e); }); }); }
export const userQuestionsPlugin = definePlugin<UserQuestionsConfig, SealHarnessEvents>({ name: "user-questions", provides: [userQuestionServiceToken], setup(context, config) { const service = new DefaultUserQuestionService(); context.provide(userQuestionServiceToken, service); if (config.answerer !== undefined) context.effect(service.registerAnswerer(config.answerer)); } });
