import { createServer } from "node:http";
import { afterEach, describe, expect, it } from "vitest";
import { HttpWebFetchProvider, isPublicIp, publicAddresses, validateUrl } from "../src/index.js";
const cleanup: Array<() => Promise<void>> = []; afterEach(async () => { for (const x of cleanup.splice(0).reverse()) await x(); });
async function fixture(): Promise<string> { const server = createServer((req, res) => { if (req.url === "/redirect") { res.writeHead(302, { location: "/page" }).end(); return; } if (req.url === "/large") { res.writeHead(200, { "content-type": "text/plain" }).end("123456789"); return; } res.writeHead(200, { "content-type": "text/html; charset=utf-8" }).end("<h1>Hello</h1>"); }); await new Promise<void>((r) => server.listen(0, "127.0.0.1", r)); cleanup.push(() => new Promise<void>((r, j) => server.close((e) => e ? j(e) : r()))); const a = server.address(); if (a === null || typeof a === "string") throw new Error(); return `http://fixture.test:${a.port}`; }
describe("HttpWebFetchProvider", () => {
  it("pins validated DNS and follows same-origin redirects", async () => { const root = await fixture(); const provider = new HttpWebFetchProvider({}, async () => [{ address: "127.0.0.1", family: 4 }]); await expect(provider.fetch({ url: `${root}/redirect` })).resolves.toMatchObject({ status: 200, body: { kind: "html", content: "<h1>Hello</h1>" }, truncated: false }); });
  it("bounds streaming bodies", async () => { const root = await fixture(); const provider = new HttpWebFetchProvider({ maxResponseBytes: 4 }, async () => [{ address: "127.0.0.1", family: 4 }]); await expect(provider.fetch({ url: `${root}/large` })).resolves.toMatchObject({ body: { content: "1234" }, truncated: true }); });
  it("blocks private address families and credentialed URLs", async () => { for (const ip of ["127.0.0.1", "10.0.0.1", "169.254.1.1", "192.168.1.1", "::1", "fd00::1", "::ffff:127.0.0.1"]) expect(isPublicIp(ip)).toBe(false); expect(isPublicIp("8.8.8.8")).toBe(true); await expect(publicAddresses("127.0.0.1")).rejects.toMatchObject({ code: "WEB_NON_PUBLIC_ADDRESS" }); expect(() => validateUrl("https://user:pass@example.com")).toThrow(); });
});
