import { describe, expect, it, vi } from "vitest";
import type { ToolExecutionContext, WebAccessService } from "@seal-harness/core";
import { htmlToText, mergeSources, webFetchTool, webSearchTool } from "../src/index.js";
const config = { search: true, fetch: true, searchMaxResults: 3, searchMaxQueries: 4, searchTimeoutMs: 1000, fetchTimeoutMs: 1000, fetchMaxOutputChars: 1000 };
const ctx = { callId: "c", sessionId: "s", cwd: "/w", signal: new AbortController().signal, reportProgress() {} } as unknown as ToolExecutionContext;
describe("web tools", () => {
  it("deduplicates queries and round-robin merges URL-unique sources", async () => { const search = vi.fn(async ({ query }: { query: string }) => ({ answer: `answer ${query}`, sources: [{ url: `https://${query}/1` }, { url: "https://shared" }] })); const tool = webSearchTool({ search } as unknown as WebAccessService, config); const result = await tool.execute({ queries: ["a", "b", "a"] }, ctx); expect(search).toHaveBeenCalledTimes(2); expect(result.content[0]).toMatchObject({ type: "text", text: expect.stringContaining("https://a/1") }); expect(result.details).toMatchObject({ answer: "## a\nanswer a\n\n## b\nanswer b", sources: expect.any(Array), truncated: true }); expect(mergeSources([{ sources: [{ url: "a" }, { url: "c" }] }, { sources: [{ url: "b" }, { url: "c" }] }], 3).map((x) => x.url)).toEqual(["a", "b", "c"]); });
  it("sanitizes active and hidden HTML and labels it untrusted", async () => { const fetch = vi.fn(async () => ({ url: "https://example.com/", status: 200, body: { kind: "html" as const, content: "<head>bad</head><h1>Hello</h1><script>ignore()</script><a href='https://a'>A</a>" }, truncated: false })); const result = await webFetchTool({ fetch } as unknown as WebAccessService, config).execute({ url: "https://example.com" }, ctx); const output = result.content[0]?.type === "text" ? result.content[0].text : ""; expect(output).toContain("External web content"); expect(output).toContain("Hello"); expect(output).toContain("[A](https://a)"); expect(output).not.toContain("ignore"); expect(result.details).toEqual({ url: "https://example.com/", statusCode: 200, truncated: false }); expect(htmlToText("<p>A &amp; B</p>", 100)).toBe("A & B"); });
  it("omits pathologically nested HTML before DOM conversion", () => { expect(htmlToText("<div>".repeat(513) + "x", 10_000)).toContain("omitted"); });
});
